name: Publish Caddy docker image

on:
  push:
    branches: ['main']
    # paths: ['caddy/**']

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: antonchristensen
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Package and push
        uses: docker/build-push-action@v6
        with:
          context: ./caddy
          push: true
          provenance: false
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Commit message: ${{ github.event.head_commit.message }}
          tags: |
            antonchristensen/portfolio:latest
            antonchristensen/portfolio:${{ github.sha }}